daily_tasks = {
    1: "Start your day by repeating your affirmations to yourself 3 times while you tap your head.",
    2: "Remind yourself of the long-term goals you've set for yourself after MIH. Write them out to begin your day.",
    3: "Think about the strengths, talents, and positive qualities/skills that you think you have exhibited today.",
    4: "Take out time to meditate today.",
    5: "Write out 3 of your key strengths and leave the note in a prominent area of your workspace.",
    6: "Reflect on a situation that caused you some uncertainty in your day. Map it out at the body, mind, and spiritual levels. Try to identify the area of inner conflict.",
    7: "Introspect on your past week. What were the most impactful emotions or incidents and what strengths/weaknesses do they reveal to you?",
    8: "Write your affirmations out 3 times, remembering to have conviction and belief in what you are writing.",
    9: "In the next few days, try to be aware of the situations in your day where you feel that your effort does not achieve the outcome you desire. Journal them.",
    10: "Using the situations you identified, try to recognize what you perceived as inefficiencies and limiting factors.",
    11: "Meditate today thinking about the guidance, love, and blessings of our gurus, ever-present in our life.",
    12: "Practice a mindfulness task in an area of your choice.",
    13: "Try to be aware of and avoid using language/limiting words that you may tend to use today.",
    14: "Today, try a substitute for the words you found yourself using with more positive, affirmative language.",
    15: "Begin your day by repeating your affirmations to yourself 3 times while you tap your head.",
    16: "Reflect on what you feel grateful for today. Recognize how this sense of gratitude makes you feel. How can this help you in overcoming your limiting beliefs?",
    17: "Today, practice silence for a duration of your choice, and observe the changes in your mind.",
    18: "Meditate today, thinking about your Ishta Devata, considering the qualities you admire and would like to imbibe in yourself.",
    19: "Choose a person/activity where you will try to focus on acting from a perspective of head and heart integration today.",
    20: "Today, practice a reflection on a positive action/outcome, experience, or emotion that comes to mind.",
    21: "Reflect on your day and identify what you see as inefficiencies in your daily routine. How can you change or improve this if you feel that is required?",
    22: "Write your affirmations out 3 times, remembering to have conviction and belief in what you are writing.",
    23: "Today, think about any current situations which require you to work in a team. Reflect on your understanding of the common goal/purpose and your role in working towards achieving that goal.",
    24: "Repeat the head and heart integration activity today, using something from your garden.",
    25: "Try a walking meditation out in nature today. Focus on what you identified as your 3 major achievements during MIH.",
    26: "Start your day by repeating your affirmations to yourself 3 times while you tap your head.",
    27: "Try to practice mindfulness in a task today which you perceive as stressful/challenging.",
    28: "Reflect on your mindfulness activity from yesterday. Do you feel that it affected the process or outcome of your tasks?",
    29: "Meditate today, focusing on your affirmations. Remember the positive emotions associated with them. Picture them helping you overcome any limitations you perceive.",
    30: "Remind yourself of the long-term goal(s) you've set for yourself after MIH. Write them out to begin your day!",
    31: "Take out time to meditate today."
}
